name: Build the builder
description: |
  Builds the docker image that we'll use to do most of our building.
  Use the run-in-builder action to run a command in the builder.

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3

    - name: Build builder image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: .devcontainer/Dockerfile
        target: ci
        tags: builder
        load: true
        cache-from: |
          type=gha,scope=${{ github.ref_name }}-builder
          type=gha,scope=main-builder
        cache-to: type=gha,scope=${{ github.ref_name }}-builder
