{
 "title": "k6 Load Testing Results",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the Timestream exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Database", "query": "SHOW DATABASES" },
   {
    "name": "Table",
    "query": "SHOW TABLES FROM \"$Database\""
   },
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   },
   {
    "name": "Filter",
    "query": "DESCRIBE \"$Database\".\"$Table\""
   },
   { "name": "FilterValue", "label": "LIKE", "query": "%" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active VUs",
     "database": "\"$Database\"",
     "measure": "vus",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS $__measure\nFROM (\n  SELECT time, SUM($__measure) AS $__measure\n  FROM (\n    SELECT BIN(time, 1s) AS time, AVG(measure_value::double) AS $__measure, instance_id\n    FROM $__database.$__table\n    WHERE measure_name = '$__measure'\n    AND $__timeFilter\n    GROUP BY BIN(time, 1s), instance_id\n    ORDER BY BIN(time, 1s) DESC\n  )\n  GROUP BY time\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests Per Second",
     "database": "\"$Database\"",
     "measure": "http_reqs",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS $__measure\nFROM (\n  SELECT time, SUM($__measure) AS $__measure\n  FROM (\n    SELECT BIN(time, 1s) AS time, SUM(measure_value::double) AS $__measure, instance_id\n    FROM $__database.$__table\n    WHERE measure_name = '$__measure'\n    AND $__timeFilter\n    AND $Filter LIKE '$FilterValue'\n    GROUP BY BIN(time, 1s), instance_id\n    ORDER BY BIN(time, 1s) DESC\n  )\n  GROUP BY time\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Num Errors",
     "database": "\"$Database\"",
     "measure": "http_req_failed",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS $__measure_per_s\nFROM (\n  SELECT success.time, ROUND(AVG(fail_ratio.$__measure * success.http_reqs), 0) AS $__measure\n  FROM (\n    SELECT BIN(time, 1s) AS time, SUM(measure_value::double) AS http_reqs\n    FROM $__database.$__table\n    WHERE measure_name = 'http_reqs'\n    AND $__timeFilter\n    AND $Filter LIKE '$FilterValue'\n    GROUP BY BIN(time, 1s)\n    ORDER BY BIN(time, 1s) DESC\n  ) AS success,\n  (\n    SELECT BIN(time, 1s) AS time, AVG(measure_value::double) AS $__measure\n    FROM $__database.$__table\n    WHERE measure_name = '$__measure'\n    AND $__timeFilter\n    AND $Filter LIKE '$FilterValue'\n    GROUP BY BIN(time, 1s)\n    ORDER BY BIN(time, 1s) DESC\n  ) AS fail_ratio\n  WHERE fail_ratio.time = success.time\n  GROUP BY success.time\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "Data Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "data_received",
     "database": "\"$Database\"",
     "measure": "data_received",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS $__measure_per_s\nFROM (\n  SELECT time, SUM($__measure) AS $__measure\n  FROM (\n    SELECT BIN(time, 1s) AS time, SUM(measure_value::double) AS $__measure, instance_id\n    FROM $__database.$__table\n    WHERE measure_name = '$__measure'\n    AND $__timeFilter\n    AND $Filter LIKE '$FilterValue'\n    GROUP BY BIN(time, 1s), instance_id\n    ORDER BY BIN(time, 1s) DESC\n  )\n  GROUP BY time\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    },
    {
     "alias": "data_sent",
     "database": "\"$Database\"",
     "measure": "data_sent",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS $__measure_per_s\nFROM (\n  SELECT time, SUM($__measure) AS $__measure\n  FROM (\n    SELECT BIN(time, 1s) AS time, SUM(measure_value::double) AS $__measure, instance_id\n    FROM $__database.$__table\n    WHERE measure_name = '$__measure'\n    AND $__timeFilter\n    AND $Filter LIKE '$FilterValue'\n    GROUP BY BIN(time, 1s), instance_id\n    ORDER BY BIN(time, 1s) DESC\n  )\n  GROUP BY time\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Measurement",
   "targets": [
    {}
   ]
  },
  {
   "title": "$Measurement (mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT AVG(measure_value::double) AS $__measure\nFROM $__database.$__table\nWHERE measure_name = '$__measure'\nAND $__timeFilter\nAND $Filter LIKE '$FilterValue'",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT MAX(measure_value::double) AS $__measure\nFROM $__database.$__table\nWHERE measure_name = '$__measure'\nAND $__timeFilter\nAND $Filter LIKE '$FilterValue'",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT APPROX_PERCENTILE(measure_value::double, 0.5) AS $__measure\nFROM $__database.$__table\nWHERE measure_name = '$__measure'\nAND $__timeFilter\nAND $Filter LIKE '$FilterValue'",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT MIN(measure_value::double) AS $__measure\nFROM $__database.$__table\nWHERE measure_name = '$__measure'\nAND $__timeFilter\nAND $Filter LIKE '$FilterValue'\n",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement (p90)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT APPROX_PERCENTILE(measure_value::double, 0.9) AS $__measure\nFROM $__database.$__table\nWHERE measure_name = '$__measure'\nAND $__timeFilter\nAND $Filter LIKE '$FilterValue'",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT APPROX_PERCENTILE(measure_value::double, 0.95) AS $__measure\nFROM $__database.$__table\nWHERE measure_name = '$__measure'\nAND $__timeFilter\nAND $Filter LIKE '$FilterValue'",
     "table": "\"$Table\""
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "max",
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS \"max\"\nFROM (\n  SELECT BIN(time, 1s) AS time, MAX(measure_value::double) AS $__measure\n  FROM $__database.$__table\n  WHERE measure_name = '$__measure'\n  AND $__timeFilter\n  AND $Filter LIKE '$FilterValue'\n  GROUP BY BIN(time, 1s)\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    },
    {
     "alias": "p95",
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS p95\nFROM (\n  SELECT BIN(time, 1s) AS time, APPROX_PERCENTILE(measure_value::double, 0.95) AS $__measure\n  FROM $__database.$__table\n  WHERE measure_name = '$__measure'\n  AND $__timeFilter\n  AND $Filter LIKE '$FilterValue'\n GROUP BY BIN(time, 1s)\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    },
    {
     "alias": "p90",
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS p90\nFROM (\n  SELECT BIN(time, 1s) AS time, APPROX_PERCENTILE(measure_value::double, 0.90) AS $__measure\n  FROM $__database.$__table\n  WHERE measure_name = '$__measure'\n  AND $__timeFilter\n  AND $Filter LIKE '$FilterValue'\n  GROUP BY BIN(time, 1s)\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    },
    {
     "alias": "min",
     "database": "\"$Database\"",
     "measure": "$Measurement",
     "rawQuery": "SELECT BIN(time, $__interval) AS time, AVG($__measure) AS \"min\"\nFROM (\n  SELECT BIN(time, 1s) AS time, MIN(measure_value::double) AS $__measure\n  FROM $__database.$__table\n  WHERE measure_name = '$__measure'\n  AND $__timeFilter \n  AND $Filter LIKE '$FilterValue'\n GROUP BY BIN(time, 1s)\n)\nGROUP BY BIN(time, $__interval)",
     "table": "\"$Table\""
    }
   ]
  }
 ]
}