name: Integration tests
description: |
  Runs the inregration tests by deploying to AWS, running the tests and destroying

inputs:
  image:
    description: Docker image to use for K6
    required: true
  region:
    description: AWS Region to run tests in
    required: false
  aws-role-arn:
    description: AWS Role ARN to perform actions in AWS
    required: true
  git-sha:
    description: The git SHA we're building
    required: false

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: us-east-1

    - name: Deploy (cross-region)
      shell: nix develop -c bash -e {0}
      run: make AWS_REGION=${K6_TIMESTREAM_REGION} deploy-infra
      if: "${{ env.K6_TIMESTREAM_REGION != '' }}"
      env:
        K6_TIMESTREAM_REGION: ${{ inputs.region }}
        K6_TIMESTREAM_DATABASE_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        K6_TIMESTREAM_TABLE_NAME: test
        INFRA_STACK_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        ENV: ci

    - name: Deploy
      shell: nix develop -c bash -e {0}
      run: make deploy-infra
      if: "${{ env.K6_TIMESTREAM_REGION == '' }}"
      env:
        K6_TIMESTREAM_REGION: ${{ inputs.region }}
        K6_TIMESTREAM_DATABASE_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        K6_TIMESTREAM_TABLE_NAME: test
        INFRA_STACK_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        ENV: ci

    - name: Integration Tests
      shell: nix develop -c bash -e {0}
      run: make FULL_IMAGE_NAME=${{ inputs.image }} test-integration
      env:
        K6_TIMESTREAM_REGION: ${{ inputs.region }}
        K6_TIMESTREAM_DATABASE_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        K6_TIMESTREAM_TABLE_NAME: test
        INFRA_STACK_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        ENV: ci

    - name: Destroy (cross-region)
      shell: nix develop -c bash -e {0}
      run: make AWS_REGION=${K6_TIMESTREAM_REGION} destroy-infra
      if: "${{ always() && env.K6_TIMESTREAM_REGION != '' }}"
      env:
        K6_TIMESTREAM_REGION: ${{ inputs.region }}
        K6_TIMESTREAM_DATABASE_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        K6_TIMESTREAM_TABLE_NAME: test
        INFRA_STACK_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        ENV: ci

    - name: Destroy
      shell: nix develop -c bash -e {0}
      run: make destroy-infra
      if: "${{ always() && env.K6_TIMESTREAM_REGION == '' }}"
      env:
        K6_TIMESTREAM_REGION: ${{ inputs.region }}
        K6_TIMESTREAM_DATABASE_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        K6_TIMESTREAM_TABLE_NAME: test
        INFRA_STACK_NAME:
          github-xk6-output-timestream-${{ inputs.git-sha || github.sha }}
        ENV: ci
