name: Build
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: false
      builder_image:
        type: string
        required: true
      image:
        type: string
        required: true
      executable_name:
        type: string
        required: true
      platform:
        type: string
        required: false
        default: ""
    outputs:
      image:
        description: The built image
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      platform: ${{ inputs.platform }}
      builder_image: ${{ inputs.builder_image }}
      image: ${{ inputs.image }}

  upload-executable:
    runs-on: ubuntu-22.04
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
      - name: Login ghcr.io
        shell: bash
        run: docker login --username ${{ github.repository_owner }} --password ${{ github.token }} ghcr.io
      - name: Pull image
        shell: bash
        run: docker pull ${{ needs.build.outputs.image }}
      - run: |
          make \
            FULL_IMAGE_NAME=${{ needs.build.outputs.image }} \
            CACHE_NAME=${{ inputs.builder_image }} \
            PLATFORM=${{ inputs.platform }} \
            copy-k6-from-image
        env:
          K6_LOCATION: ./${{ inputs.executable_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.executable_name }}
          path: ./${{ inputs.executable_name }}
    needs:
      - build
