name: Build
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: false
      builder_image:
        type: string
        required: true
      image:
        type: string
        required: true
      platform:
        type: string
        required: false
        default: ""
    outputs:
      image:
        description: The built image
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: "read"
      packages: "write"
    outputs:
      image: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login ghcr.io
        shell: bash
        run: docker login --username ${{ github.repository_owner }} --password ${{ github.token }} ghcr.io
      - name: Pull builder
        shell: bash
        run: docker pull ${{ inputs.builder_image }}
      - run: |
          make \
            FULL_IMAGE_NAME=${{ inputs.image }} \
            CACHE_NAME=${{ inputs.builder_image }} \
            PLATFORM=${{ inputs.platform }} \
            build-image \
            push-image
