name: Release
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: false
      builder_image:
        type: string
        required: true
    secrets:
      SSH_KEY_GITHUB:
        required: true

jobs:
  release:
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.builder_image }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed so that we trigger the version tag action - see
          # https://github.com/orgs/community/discussions/27028#discussioncomment-3254367
          ssh-key: "${{ secrets.SSH_KEY_GITHUB }}"
          ref: ${{ inputs.git_ref }}
          fetch-depth: 0
      # See https://github.com/actions/runner/issues/2033
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: make release-tag
