# Note that get this to run you need to follow the instructions
# in https://github.com/orgs/community/discussions/27028#discussioncomment-3254367
name: Build on Push (version tag)
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  packages: write

jobs:
  create-changelog:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}-ci-builder:${{ github.sha }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # See https://github.com/actions/runner/issues/2033
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: make changelog
      - uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md

  release:
    runs-on: ubuntu-22.04
    needs:
      - create-changelog
    steps:
      - uses: actions/checkout@v3
      - name: Download CHANGELOG
        uses: actions/download-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./
      - name: Download k6 executable (x86_64)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: push-main.yaml
          workflow_conclusion: success
          commit: ${{github.sha}}
          name: k6
      - name: Login ghcr.io
        run: docker login --username ${{ github.repository_owner }} --password ${{ github.token }} ghcr.io
      - name: Pull built CI image to cache
        run: docker pull ghcr.io/${{ github.repository_owner }}/k6:${{ github.sha }}
      - name: Tag cached image
        run: |
          make \
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/k6 \
            VERSION=${{ github.ref_name }} \
            CACHE_NAME=ghcr.io/${{ github.repository_owner }}/k6:${{ github.sha }} \
            tag-cached-image \
            push-image
      - name: Update changelog with tagged image
        run: |
          make \
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/k6 \
            VERSION=${{ github.ref_name }} \
            update-changelog
      - name: Pull built CI grafana image to cache
        run: docker pull ghcr.io/${{ github.repository_owner }}/grafana-oss:${{ github.sha }}
      - name: Tag cached grafana image
        run: |
          make \
            GRAFANA_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/grafana-oss \
            VERSION=${{ github.ref_name }} \
            CACHE_NAME=ghcr.io/${{ github.repository_owner }}/grafana-oss:${{ github.sha }} \
            grafana-tag-cached-image \
            grafana-push-image
      - name: Update changelog with tagged grafana image
        run: |
          make \
            GRAFANA_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/grafana-oss \
            VERSION=${{ github.ref_name }} \
            grafana-update-changelog
      - run: make VERSION=${{ github.ref_name }} release-github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          K6_LOCATION: "./k6"

  release-go-package:
    needs:
      - release
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}-ci-builder:${{ github.sha }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - run: make VERSION=${{ github.ref_name }} release-go
