# Note that get this to run you need to follow the instructions
# in https://github.com/orgs/community/discussions/27028#discussioncomment-3254367
name: Build on Push (version tag)
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release-go-package:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.19.3-buster
    steps:
      - uses: actions/checkout@v3
      - run: make VERSION=${{ github.ref_name }} release-go
  create-changelog:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}-ci-builder:${{ github.sha }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make changelog
      - uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
  release-github:
    runs-on: ubuntu-22.04
    needs:
      - create-changelog
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: push-main.yaml
          workflow_conclusion: success
          commit: ${{github.sha}}
          name: k6
      - name: Login ghcr.io
        shell: bash
        run: docker login --username ${{ github.repository_owner }} --password ${{ github.token }} ghcr.io
      - run: docker pull ghcr.io/${{ github.repository_owner }}/k6:${{ github.sha }}
      - run: docker pull ghcr.io/${{ github.repository }}-ci-builder:${{ github.sha }}
      - run: |
          make \
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/k6 \
            CACHE_NAME="ghcr.io/${{ github.repository_owner }}/k6:${{ github.sha }} --cache-from ghcr.io/${{ github.repository }}-ci-builder:${{ github.sha }}" \
            build-image \
            push-image
      - run: |
          make \
            IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/k6 \
            update-changelog
      - run: make VERSION=${{ github.ref_name }} release-github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          K6_LOCATION: "./k6"
