name: Validate
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main

permissions:
  contents: "read"

defaults:
  run:
    shell: nix develop -c bash -e {0}

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: echo "Installed dependencies"

      - name: Lint
        run: pre-commit run --all-files

      - name: Unit test
        run: make test-unit
